#!/bin/zsh

# Display the weather inside your terminal:
alias weather='curl wttr.in/$POSTCODE'

alias steamdeck='ssh deck@steamdeck'

alias hx='helix'

alias whereami='curl ipinfo.io'


# mkdir and cd into it:
mkcdir() {
    mkdir -p -- "$1" &&
    cd -P -- "$1" || exit
}

repos() {
    cd ~/Documents/repos
}

dots(){
    if [ "$1" = "edit" ]; then
        cd ~/Documents/repos/Elements-Gaming-Rig && helix .
    elif [ "$1" = "view" ]; then
        cd ~/Documents/repos/Elements-Gaming-Rig
    else
        echo "Usage: dotfiles [edit|view]"
    fi
}

# ====================
#     Env vars
# ====================

export EDITOR=/usr/bin/helix
export VISUAL=/usr/bin/helix
